Sails check every connection when lift even unused
I had problems to deploy sails to heroku with ORM connection to MongoLab:
```
Error: Failed to connect to MongoDB. Are you sure your configured Mongo instance is running?
Error details:
{ [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
name: 'MongoError',
message: 'connect ECONNREFUSED 127.0.0.1:27017' }
at createError (/home/leosuncin/Workspaces/github/sails-issue-3581/node_modules/sails-mongo/lib/adapter.js:103:23)
at /home/leosuncin/Workspaces/github/sails-issue-3581/node_modules/sails-mongo/lib/adapter.js:106:13
at /home/leosuncin/Workspaces/github/sails-issue-3581/node_modules/sails-mongo/lib/connection.js:25:20
at /home/leosuncin/Workspaces/github/sails-issue-3581/node_modules/mongodb/lib/mongo_client.js:276:20
at /home/leosuncin/Workspaces/github/sails-issue-3581/node_modules/mongodb/lib/db.js:224:14
at [object Object]. (/home/leosuncin/Workspaces/github/sails-issue-3581/node_modules/mongodb/lib/server.js:234:9)
at [object Object].g (events.js:273:16)
at emitTwo (events.js:100:13)
at [object Object].emit (events.js:185:7)
at [object Object]. (/home/leosuncin/Workspaces/github/sails-issue-3581/node_modules/mongodb-core/lib/topologies/server.js:269:68)
at [object Object].g (events.js:273:16)
at emitTwo (events.js:100:13)
at [object Object].emit (events.js:185:7)
at [object Object]. (/home/leosuncin/Workspaces/github/sails-issue-3581/node modules/mongodb-core/lib/connection/pool.js:81:12)
at [object Object].g (events.js:273:16)
at emitTwo (events.js:100:13)
at [object Object].emit (events.js:185:7)
at Socket. (/home/leosuncin/Workspaces/github/sails-issue-3581/node_modules/mongodb-core/lib/connection/connection.js:124:49)
at Socket.g (events.js:273:16)
at emitOne (events.js:90:13)
at Socket.emit (events.js:182:7)
at emitErrorNT (net.js:1246:8)
at nextTickCallbackWith2Args (node.js:475:9)
at process._tickDomainCallback (node.js:430:17)
{ [Error: Failed to connect to MongoDB. Are you sure your configured Mongo instance is running?
Error details:
{ [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
name: 'MongoError',
message: 'connect ECONNREFUSED 127.0.0.1:27017' }]
originalError:
{ [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
name: 'MongoError',
message: 'connect ECONNREFUSED 127.0.0.1:27017' } }
ad hoc redis client ready (pub) (1337)
/home/leosuncin/Workspaces/github/sails-issue-3581/node_modules/mongodb/lib/mongo_client.js:444
throw err
^

TypeError: Cannot set property 'connection' of undefined
at /home/leosuncin/Workspaces/github/sails-issue-3581/node_modules/sails-mongo/lib/adapter.js:108:53
at /home/leosuncin/Workspaces/github/sails-issue-3581/node_modules/sails-mongo/lib/connection.js:32:5
at /home/leosuncin/Workspaces/github/sails-issue-3581/node_modules/mongodb/lib/mongo_client.js:441:15
at nextTickCallbackWith0Args (node.js:453:9)
at process._tickDomainCallback (node.js:423:13)
```

https://github.com/balderdashy/sails/issues/3581 ( https://github.com/balderdashy/sails/issues/3581 )